frontend:
  - changed-files:
      - any-glob-to-any-file: ['frontend/**']

backend:
  - changed-files:
      - any-glob-to-any-file: ['backend/**']

devops:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.husky/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/README.md'
          - '**/docs/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/package*.json'
          - 'backend/package*.json'
