/*
This file is Exports hooks for OpenAPI endpoints using the api client.
It is most certain that this file is not bugged.
Do not edit this file manually.
*/

import { api } from '../lib/openapi';
import { components } from '../types/schema';
import { useState } from 'react';

// import type { QuestionRenderView, SaveQuestion, SubmitQuizResponse, QuizSubmissionResponse, FlaggedQuestionResponse, UserQuizMetrics, QuizDetails, QuizAnalytics, QuizPerformance, QuizResults } from '../types/quiz.types';
// import type {
//   NewAnomalyData,
//   AnomalyData,
//   DeleteAnomalyBody
// } from '@/types/reportanomaly.types';
// import type { ProctoringSettings } from '@/types/video.types';
// import { InviteBody, InviteResponse, MessageResponse } from '@/types/invite.types';

// Auth hooks

// POST /auth/verify
export function useLogin(): {
  data: undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("post", "/api/auth/login", {});

  return {
    data: undefined,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Login failed') : null,
    refetch: result.refetch
  };
}

// POST /auth/google
export function useLoginWithGoogle(): {
  mutate: (variables: { body: { lastName: string, firstName: string, email: string } }) => void,
  mutateAsync: (variables: { body: { lastName: string, firstName: string, email: string } }) => Promise<components['schemas']['SignUpResponse']>,
  data: components['schemas']['SignUpResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/auth/signup/google");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Google login failed') : null
  };
}

// POST /auth/signup
export function useSignup(): {
  mutate: (variables: { body: components['schemas']['SignUpBody'] }) => void,
  mutateAsync: (variables: { body: components['schemas']['SignUpBody'] }) => Promise<components['schemas']['SignUpResponse']>,
  data: components['schemas']['SignUpResponse'] | undefined,
  error: unknown | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/auth/signup");
  return {
    ...result,
    error: result.error ? (result.error) : null
  };
}

// POST /auth/signup/verify
export function useVerifySignUpProvider(): {
  mutate: (variables: { body: components['schemas']['VerifySignUpProviderBody'] }) => void,
  mutateAsync: (variables: { body: components['schemas']['VerifySignUpProviderBody'] }) => Promise<components['schemas']['SignUpResponse']>,
  data: components['schemas']['SignUpResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/auth/signup/verify");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Verification failed') : null
  };
}

// PATCH /auth/change-password
export function useChangePassword(): {
  mutate: (variables: { body: components['schemas']['ChangePasswordBody'] }) => void,
  mutateAsync: (variables: { body: components['schemas']['ChangePasswordBody'] }) => Promise<components['schemas']['ChangePasswordResponse']>,
  data: components['schemas']['ChangePasswordResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/auth/change-password");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Password change failed') : null
  };
}

// Course hooks

// POST /courses/
export function useCreateCourse(): {
  mutate: (variables: { body: components['schemas']['CourseBody'] }) => void,
  mutateAsync: (variables: { body: components['schemas']['CourseBody'] }) => Promise<components['schemas']['CourseDataResponse']>,
  data: components['schemas']['CourseDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/courses/");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Course creation failed') : null
  };
}

// GET /courses/{id}
export function useCourseById(id: string): {
  data: components['schemas']['CourseDataResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/courses/{courseId}", {
    params: { path: { courseId: id } }
  }, { enabled: !!id });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch course') : null,
    refetch: result.refetch
  };
}

// PUT /courses/{id}
export function useUpdateCourse(): {
  mutate: (variables: { params: { path: { courseId: string } }, body: components['schemas']['CourseBody'] }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string } }, body: components['schemas']['CourseBody'] }) => Promise<components['schemas']['CourseDataResponse']>,
  data: components['schemas']['CourseDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/{courseId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Course update failed') : null
  };
}

// DELETE /courses/{id}
export function useDeleteCourse(): {
  mutate: (variables: { params: { path: { courseId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string } } }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/courses/{courseId}") as ReturnType<
    () => {
      mutate: (variables: { params: { path: { courseId: string } } }) => void;
      mutateAsync: (variables: { params: { path: { courseId: string } } }) => Promise<void>;
      data: void | undefined;
      error: string | null;
      isPending: boolean;
      isSuccess: boolean;
      isError: boolean;
      isIdle: boolean;
      reset: () => void;
      status: "idle" | "pending" | "success" | "error";
    }
  >;

  return {
    ...result,
    error: result.error ? (result.error || 'Failed to delete course') : null
  };
}


// Course Version hooks

// POST /courses/{id}/versions
export function useCreateCourseVersion(): {
  mutate: (variables: { params: { path: { courseId: string } }, body: components['schemas']['CreateCourseVersionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string } }, body: components['schemas']['CreateCourseVersionBody'] }) => Promise<components['schemas']['CourseVersion']>,
  data: components['schemas']['CourseVersion'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/courses/{courseId}/versions");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Course version creation failed') : null
  };
}

// GET /courses/versions/{id}
export function useCourseVersionById(id: string): {
  data: components['schemas']['CourseVersion'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/courses/versions/{id}", {
    params: { path: { id } }
  }, { enabled: !!id }
  );

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch course version') : null,
    refetch: result.refetch
  };
}

// DELETE /courses/{courseId}/versions/{versionId}
export function useDeleteCourseVersion(): {
  mutate: (variables: { params: { path: { courseId: string, versionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string, versionId: string } } }) => Promise<components['schemas']['DeleteCourseVersionResponse']>,
  data: components['schemas']['DeleteCourseVersionResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/courses/{courseId}/versions/{versionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Course version deletion failed') : null
  };
}

// Module hooks

// POST /courses/versions/{versionId}/modules
export function useCreateModule(): {
  mutate: (variables: { params: { path: { versionId: string } }, body: components['schemas']['CreateModuleBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string } }, body: components['schemas']['CreateModuleBody'] }) => Promise<components['schemas']['ModuleDataResponse']>,
  data: components['schemas']['ModuleDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/courses/versions/{versionId}/modules");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Module creation failed') : null
  };
}

// PUT /courses/versions/{versionId}/modules/{moduleId}
export function useUpdateModule(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string } }, body: components['schemas']['UpdateModuleBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string } }, body: components['schemas']['UpdateModuleBody'] }) => Promise<components['schemas']['ModuleDataResponse']>,
  data: components['schemas']['ModuleDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/versions/{versionId}/modules/{moduleId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Module update failed') : null
  };
}

// DELETE /courses/versions/{versionId}/modules/{moduleId}
export function useDeleteModule(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string } } }) => Promise<components['schemas']['ModuleDeletedResponse']>,
  data: components['schemas']['ModuleDeletedResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/courses/versions/{versionId}/modules/{moduleId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Module deletion failed') : null
  };
}

// PUT /courses/versions/{versionId}/modules/{moduleId}/move
export function useMoveModule(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string } }, body: components['schemas']['MoveModuleBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string } }, body: components['schemas']['MoveModuleBody'] }) => Promise<components['schemas']['ModuleDataResponse']>,
  data: components['schemas']['ModuleDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/versions/{versionId}/modules/{moduleId}/move");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Module move failed') : null
  };
}

// Section hooks

// POST /courses/versions/{versionId}/modules/{moduleId}/sections
export function useCreateSection(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string } }, body: components['schemas']['CreateSectionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string } }, body: components['schemas']['CreateSectionBody'] }) => Promise<components['schemas']['CourseVersion']>,
  data: components['schemas']['CourseVersion'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/courses/versions/{versionId}/modules/{moduleId}/sections");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Section creation failed') : null
  };
}

// PUT /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}
export function useUpdateSection(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } }, body: components['schemas']['UpdateSectionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } }, body: components['schemas']['UpdateSectionBody'] }) => Promise<components['schemas']['CourseVersion']>,
  data: components['schemas']['CourseVersion'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Section update failed') : null
  };
}

// DELETE /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}
export function useDeleteSection(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } } }) => Promise<components['schemas']['SectionDeletedResponse']>,
  data: components['schemas']['SectionDeletedResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Section deletion failed') : null
  };
}

// PUT /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/move
export function useMoveSection(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } }, body: components['schemas']['MoveSectionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } }, body: components['schemas']['MoveSectionBody'] }) => Promise<components['schemas']['CourseVersion']>,
  data: components['schemas']['CourseVersion'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/move");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Section move failed') : null
  };
}

// Item hooks

// GET /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items
export function useItemsBySectionId(versionId: string, moduleId: string, sectionId: string): {
  data: components['schemas']['ItemDataResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items", {
    params: { path: { versionId, moduleId, sectionId } }
  }, { enabled: !!versionId && !!moduleId && !!sectionId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch items') : null,
    refetch: result.refetch
  };
}

// POST /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items
export function useCreateItem(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } }, body: components['schemas']['CreateItemBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string } }, body: components['schemas']['CreateItemBody'] }) => Promise<components['schemas']['ItemDataResponse']>,
  data: components['schemas']['ItemDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Item creation failed') : null
  };
}

// GET /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items/{itemId}
export function useItemById(courseId: string, versionId: string, itemId: string): {
  data: components['schemas']['GetItemResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/courses/{courseId}/versions/{versionId}/item/{itemId}", {
    params: { path: { courseId, versionId, itemId } }
  }, { enabled: !!courseId && !!versionId && !!itemId }
  );
  // console.log("here", courseId , versionId , itemId);
  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message ? result.error.message : "ERROR HERE") : null,
    refetch: result.refetch
  };
}

// PUT /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items/{itemId}
export function useUpdateItem(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string, itemId: string } }, body: components['schemas']['UpdateItemBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string, itemId: string } }, body: components['schemas']['UpdateItemBody'] }) => Promise<components['schemas']['ItemDataResponse']>,
  data: components['schemas']['ItemDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items/{itemId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Item update failed') : null
  };
}

// DELETE /courses/itemGroups/{itemsGroupId}/items/{itemId}
export function useDeleteItem(): {
  mutate: (variables: { params: { path: { itemsGroupId: string, itemId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { itemsGroupId: string, itemId: string } } }) => Promise<components['schemas']['DeletedItemResponse']>,
  data: components['schemas']['DeletedItemResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/courses/itemGroups/{itemsGroupId}/items/{itemId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Item deletion failed') : null
  };
}

// PUT /courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items/{itemId}/move
export function useMoveItem(): {
  mutate: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string, itemId: string } }, body: components['schemas']['MoveItemBody'] }) => void,
  mutateAsync: (variables: { params: { path: { versionId: string, moduleId: string, sectionId: string, itemId: string } }, body: components['schemas']['MoveItemBody'] }) => Promise<components['schemas']['ItemDataResponse']>,
  data: components['schemas']['ItemDataResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/courses/versions/{versionId}/modules/{moduleId}/sections/{sectionId}/items/{itemId}/move");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Item move failed') : null
  };
}

// Enrollment hooks

// POST /users/{userId}/enrollments/courses/{courseId}/versions/{versionId}
export function useEnrollUser(): {
  mutate: (variables: { params: { path: { userId: string, courseId: string, versionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { userId: string, courseId: string, versionId: string } } }) => Promise<components['schemas']['EnrollUserResponse']>,
  data: components['schemas']['EnrollUserResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/users/{userId}/enrollments/courses/{courseId}/versions/{versionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'User enrollment failed') : null
  };
}

// POST /users/{userId}/enrollments/courses/{courseId}/versions/{courseVersionId}/unenroll
export function useUnenrollUser(): {
  mutate: (variables: { params: { path: { userId: string, courseId: string, versionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { userId: string, courseId: string, versionId: string } } }) => Promise<components['schemas']['EnrollUserResponse']>,
  data: components['schemas']['EnrollUserResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/users/{userId}/enrollments/courses/{courseId}/versions/{versionId}/unenroll");
  return {
    ...result,
    error: result.error ? (result.error.message || 'User unenrollment failed') : null
  };
}

// GET /users/enrollments
export function useUserEnrollments(page?: number, limit?: number, enabled: boolean = true): {
  data: components['schemas']['EnrollmentResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/users/enrollments", {
    params: {
      query: { page, limit }
    },
    enabled: enabled
  });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch user enrollments') : null,
    refetch: result.refetch
  };
}

// GET /enrollments/courses/{courseId}/versions/{courseVersionId}
export function useCourseVersionEnrollments(courseId: string | undefined, courseVersionId: string | undefined, page?: number, limit?: number, enabled: boolean = true): {
  data: components['schemas']['CourseVersionEnrollmentResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  if (!courseId || !courseVersionId) {
    throw new Error("courseId and courseVersionId must be defined");
  }
  const result = api.useQuery("get", "/api/users/enrollments/courses/{courseId}/versions/{versionId}", {
    params: {
      path: { courseId, versionId: courseVersionId },
      query: { page, limit }
    },
    enabled: enabled
  });
  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch course version enrollments') : null,
    refetch: result.refetch
  };
}

// Progress hooks

// GET /users/progress/courses/{courseId}/versions/{courseVersionId}/
export function useUserProgress(courseId: string, courseVersionId: string): {
  data: components['schemas']['ProgressDataResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/users/progress/courses/{courseId}/versions/{versionId}/", {
    params: { path: { courseId, versionId: courseVersionId } }
  }, { enabled: !!courseId && !!courseVersionId }
  );

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch user progress') : null,
    refetch: result.refetch
  };
}

// GET /users/progress/courses/{courseId}/versions/{courseVersionId}/percentage
export function useUserProgressPercentage(courseId: string, courseVersionId: string): {
  data: {
    completed: boolean;
    percentCompleted: number;
    totalItems: number;
    completedItems: number;
  } | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/users/progress/courses/{courseId}/versions/{versionId}/percentage", {
    params: { path: { courseId, versionId: courseVersionId } }
  }, { enabled: !!courseId && !!courseVersionId }
  );

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch user progress percentage') : null,
    refetch: result.refetch
  };
}

// Add this hook to your hooks file
export function useUserProgressPercentageByUserId(
  userId: string,
  courseId: string,
  courseVersionId: string
): {
  data: {
    completed: boolean;
    percentCompleted: number;
    totalItems: number;
    completedItems: number;
  } | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery(
    "get",
    "/api/users/progress/courses/{courseId}/versions/{versionId}/percentage",
    {
      params: {
        path: {
          courseId,
          versionId: courseVersionId
        }
      }
    },
    {
      enabled: !!(userId && courseId && courseVersionId)
    }
  );

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch user progress percentage') : null,
    refetch: result.refetch
  };
}

// POST /users/progress/courses/{courseId}/versions/{versionId}/start
export function useStartItem(): {
  mutate: (variables: { params: { path: { courseId: string, versionId: string } }, body: components['schemas']['StartItemBody'] }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string, versionId: string } }, body: components['schemas']['StartItemBody'] }) => Promise<components['schemas']['StartItemResponse']>,
  data: components['schemas']['StartItemResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/users/progress/courses/{courseId}/versions/{versionId}/start");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to start item') : null
  };
}

// POST /users/progress/courses/{courseId}/versions/{versionId}/stop
export function useStopItem(): {
  mutate: (variables: { params: { path: { courseId: string, versionId: string } }, body: components['schemas']['StopItemBody'] }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string, versionId: string } }, body: components['schemas']['StopItemBody'] }) => Promise<unknown>,
  data: unknown | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/users/progress/courses/{courseId}/versions/{versionId}/stop");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to stop item') : null
  };
}

// PATCH /users/{userid}/progress/courses/{courseId}/versions/{versionId}/reset
export function useResetProgress(): {
  mutate: (variables: { params: { path: { userId: string, courseId: string, versionId: string } }, body: components['schemas']['ResetCourseProgressBody'] }) => void,
  mutateAsync: (variables: { params: { path: { userId: string, courseId: string, versionId: string } }, body: components['schemas']['ResetCourseProgressBody'] }) => Promise<unknown>,
  data: unknown | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/users/{userId}/progress/courses/{courseId}/versions/{versionId}/reset");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to reset progress') : null
  };
}

export function useProctoringSettings(courseId: string, versionId: string): {
  data: ProctoringSettings | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/setting/course-setting/{courseId}/{versionId}", {
    params: { path: { courseId, versionId } }
  },
    { enabled: !!courseId && !!versionId }
  );

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch user by Firebase UID') : null,
    refetch: result.refetch
  };
}

export function useEditProctoringSettings() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const editSettings = async (
    courseId: string,
    versionId: string,
    detectors: { name: string; enabled: boolean }[],
    isNew: boolean
  ) => {
    setLoading(true);
    setError(null);

    try {
      const method = 'PUT';
      const url = `${import.meta.env.VITE_BASE_URL}/setting/course-setting/${courseId}/${versionId}/proctoring`;

      const body =
      {
        detectors: detectors.map((d) => ({
          detectorName: d.name,
          settings: { enabled: d.enabled },
        })),
      };

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', 'authorization': `Bearer ${localStorage.getItem('firebase-auth-token')}` },
        body: JSON.stringify(body),
      });

      console.log('Proctoring settings response:', res);

      if (!res.ok) {
        throw new Error(`Failed to update settings: ${res.status}`);
      }

      return await res.json();
    } catch (err: any) {
      setError(err.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  return { editSettings, loading, error };
}

export function useInviteUsers(): {
  mutate: (variables: { params: { path: { courseId: string, versionId: string } }, body: components['schemas']['InviteBody'] }) => void,
  mutateAsync: (variables: { params: { path: { courseId: string, versionId: string } }, body: components['schemas']['InviteBody'] }) => Promise<components['schemas']['InviteResponse']>,
  data: components['schemas']['InviteResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/notifications/invite/courses/{courseId}/versions/{versionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to invite users') : null
  };
}

export function useCourseInvites(courseId: string, courseVersionId: string, enabled: boolean = true): {
  data: components['schemas']['InviteResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/notifications/invite/courses/{courseId}/versions/{versionId}", {
    params: { path: { courseId, versionId: courseVersionId } },
    enabled: enabled
  });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch course invites') : null,
    refetch: result.refetch
  };
}

export function useResendInvite(): {
  mutate: (variables: { params: { path: { inviteId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { inviteId: string } } }) => Promise<components['schemas']['MessageResponse']>,
  data: components['schemas']['MessageResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/notifications/invite/resend/{inviteId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to resend invite') : null
  };
}

export function useCancelInvite(): {
  mutate: (variables: { params: { path: { inviteId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { inviteId: string } } }) => Promise<components['schemas']['MessageResponse']>,
  data: components['schemas']['MessageResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/notifications/invite/cancel/{inviteId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to cancel invite') : null
  };
}

// GET /users/{id}/watchTime/item/itemId
export function useWatchTimeByItemId(userId: string, courseId: string, courseVersionId: string, itemId: string, type: string): {
  data: components["schemas"]["WatchTimeResponse"][] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/users/{userId}/watchTime/item/{itemId}/", {
    params: { path: { userId: userId, courseId: courseId, courseVersionId: courseVersionId, itemId: itemId, type: type } },
  }, { enabled: !!userId && !!itemId && !!type },);

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch watch time') : null,
    refetch: result.refetch
  };
}

export function useEditUser(): {
  mutate: (variables: { body: { firstName: string; lastName: string } }) => void,
  mutateAsync: (variables: { body: { firstName: string; lastName: string } }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/users/edit");

  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to edit user') : null
  };
}

export function useWatchtimeTotal(): {
  data: number | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/users/watchTime/total", {});

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch total watch time') : null,
    refetch: result.refetch
  };
}


// --- AnomalyController Hooks ---

// POST /anomalies/record/image
export function useReportAnomalyImage(): {
  mutate: (variables: { body: NewAnomalyData; file: File }) => void,
  mutateAsync: (variables: { body: NewAnomalyData; file: File }) => Promise<AnomalyData>,
  data: AnomalyData | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  // This assumes api.useMutation supports multipart/form-data
  const result = api.useMutation("post", "/anomalies/record/image", { isMultipart: true });
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to record anomaly image') : null
  };
}

// POST /anomalies/record/audio
export function useReportAnomalyAudio(): {
  mutate: (variables: { body: NewAnomalyData; file: File }) => void,
  mutateAsync: (variables: { body: NewAnomalyData; file: File }) => Promise<AnomalyData>,
  data: AnomalyData | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  // This assumes api.useMutation supports multipart/form-data
  const result = api.useMutation("post", "/anomalies/record/audio", { isMultipart: true });
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to record anomaly audio') : null
  };
}

// GET /anomalies/course/:courseId/version/:versionId/user/:userId
export function useUserAnomalies(courseId: string, versionId: string, userId: string): {
  data: AnomalyData[] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery(
    "get",
    "/anomalies/course/{courseId}/version/{versionId}/user/{userId}",
    { params: { path: { courseId, versionId, userId } } },
    { enabled: !!courseId && !!versionId && !!userId }
  );
  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch user anomalies') : null,
    refetch: result.refetch
  };
}

// GET /anomalies/course/:courseId/version/:versionId
export function useCourseAnomalies(courseId: string, versionId: string): {
  data: AnomalyData[] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery(
    "get",
    "/anomalies/course/{courseId}/version/{versionId}",
    { params: { path: { courseId, versionId } } },
    { enabled: !!courseId && !!versionId }
  );
  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch course anomalies') : null,
    refetch: result.refetch
  };
}

// DELETE /anomalies/:id
export function useDeleteAnomaly(): {
  mutate: (variables: { params: { path: { id: string } }, body: DeleteAnomalyBody }) => void,
  mutateAsync: (variables: { params: { path: { id: string } }, body: DeleteAnomalyBody }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/anomalies/{id}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to delete anomaly') : null
  };
}


// Question types
export interface QuestionBody {
  type: string;
  details: any;
}

export interface QuestionId {
  questionId: string;
}

export interface QuestionResponse {
  _id: string;
  type: string;
  details: any;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface FlagQuestionBody {
  reason: string;
  courseId: string;
  versionId: string;
}

export interface FlagId {
  flagId: string;
}

export interface ResolveFlagBody {
  status: 'resolved' | 'rejected';
}

// Question Bank types
export interface CreateQuestionBankBody {
  name: string;
  description?: string;
  courseId: string;
  courseVersionId: string;
  questions?: string[];
}

export interface CreateQuestionBankResponse {
  questionBankId: string;
}

export interface GetQuestionBankByIdParams {
  questionBankId: string;
}

export interface QuestionBankResponse {
  _id: string;
  name: string;
  description?: string;
  courseId: string;
  courseVersionId: string;
  questions: string[];
  createdAt: string;
  updatedAt: string;
}

export interface QuestionBankAndQuestionParams {
  questionBankId: string;
  questionId: string;
}

export interface ReplaceQuestionResponse {
  newQuestionId: string;
}

// Quiz types
export interface AddQuestionBankBody {
  questionBankId: string;
  questionsCount?: number;
}

export interface RemoveQuestionBankParams {
  quizId: string;
  questionBankId: string;
}

export interface EditQuestionBankBody {
  questionBankId: string;
  questionsCount?: number;
}

export interface GetUserMatricesParams {
  quizId: string;
  userId: string;
}

export interface QuizAttemptParam {
  quizId: string;
  attemptId: string;
}

export interface UpdateQuizSubmissionParam {
  quizId: string;
  submissionId: string;
  score: number;
}

export interface RegradeSubmissionBody {
  gradingResult: any;
}

export interface AddFeedbackParams {
  quizId: string;
  submissionId: string;
  questionId: string;
}

export interface AddFeedbackBody {
  feedback: string;
}

export interface GetAllQuestionBanksResponse {
  questionBanks: Array<{
    questionBankId: string;
    questionsCount?: number;
  }>;
}

// Attempt types
export interface CreateAttemptParams {
  quizId: string;
}

export interface SaveAttemptParams {
  quizId: string;
  attemptId: string;
}

export interface SubmitAttemptParams {
  quizId: string;
  attemptId: string;
}

export interface QuestionAnswersBody {
  answers: SaveQuestion[];
}

// --- Question Controller Hooks ---
// Quiz hooks
export function useAttemptQuiz(): {
  mutate: (variables: { params: { path: { quizId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string } } }) => Promise<components['schemas']['CreateAttemptResponse']>,
  data: components['schemas']['CreateAttemptResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/{quizId}/attempt");
  return {
    mutate: result.mutate,
    mutateAsync: result.mutateAsync,
    data: result.data,
    isPending: result.isPending,
    isSuccess: result.isSuccess,
    isError: result.isError,
    isIdle: result.isIdle,
    reset: result.reset,
    status: result.status,
    error: result.error ? (result.error.message || 'Failed to attempt quiz') : null
  };
}

export function useFlagQuestion(): {
  mutate: (variables: { params: { path: { questionId: string } }, body: components['schemas']['FlagQuestionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { questionId: string } }, body: components['schemas']['FlagQuestionBody'] }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/questions/{questionId}/flag");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to flag question') : null
  };
}


export function useSaveQuiz(): {
  mutate: (variables: { params: { path: { quizId: string, attemptId: string } }, body: components['schemas']['QuestionAnswersBody'] }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string, attemptId: string } }, body: components['schemas']['QuestionAnswersBody'] }) => Promise<void>,
  data: void,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/{quizId}/attempt/{attemptId}/save");
  return {
    mutate: result.mutate,
    mutateAsync: result.mutateAsync,
    data: result.data,
    isPending: result.isPending,
    isSuccess: result.isSuccess,
    isError: result.isError,
    isIdle: result.isIdle,
    reset: result.reset,
    status: result.status,
    error: result.error ? (result.error.message || 'Failed to attempt quiz') : null
  };
}

export function useSubmitQuiz(): {
  mutate: (variables: { params: { path: { quizId: string, attemptId: string } }, body: components['schemas']['QuestionAnswersBody'] }) => components['schemas']['SubmitAttemptResponse'],
  mutateAsync: (variables: { params: { path: { quizId: string, attemptId: string } }, body: components['schemas']['QuestionAnswersBody'] }) => Promise<components['schemas']['SubmitAttemptResponse']>,
  data: components['schemas']['SubmitAttemptResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/{quizId}/attempt/{attemptId}/submit");
  return {
    mutate: result.mutate,
    mutateAsync: result.mutateAsync,
    data: result.data,
    isPending: result.isPending,
    isSuccess: result.isSuccess,
    isError: result.isError,
    isIdle: result.isIdle,
    reset: result.reset,
    status: result.status,
    error: result.error ? (result.error.message || 'Failed to attempt quiz') : null
  };
}

// GET /quizzes/{quizId}/user/{userId}
export function useUserQuizMetrics(quizId: string, userId: string): {
  data: components['schemas']['UserQuizMetricsResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/user/{userId}", {
    params: { path: { quizId, userId } }
  }, { enabled: !!quizId && !!userId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message ? result.error.message : "ERROR HERE") : null,
    refetch: result.refetch
  };
}

// GET /quiz/{quizId}/submissions/{submissionId}
export function useQuizSubmission(quizId: string, submissionId: string): {
  data: components['schemas']['QuizSubmissionResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/submissions/{submissionId}", {
    params: { path: { quizId, submissionId } }
  }, { enabled: !!quizId && !!submissionId }
  );

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error ? result.error : "Cannot fetch Quiz submission details.") : null,
    refetch: result.refetch
  };
}


// GET /quizzes/questions/{questionId}
export function useQuestionById(questionId: string): {
  data: components['schemas']['QuestionResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/questions/{questionId}", {
    params: { path: { questionId } }
  }, { enabled: !!questionId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch question') : null,
    refetch: result.refetch
  };
}

// PUT /quizzes/questions/{questionId}
export function useUpdateQuestion(): {
  mutate: (variables: { params: { path: { questionId: string } }, body: components['schemas']['QuestionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { questionId: string } }, body: components['schemas']['QuestionBody'] }) => Promise<components['schemas']['QuestionResponse']>,
  data: components['schemas']['QuestionResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("put", "/api/quizzes/questions/{questionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Question update failed') : null
  };
}

// DELETE /quizzes/questions/{questionId}
export function useDeleteQuestion(): {
  mutate: (variables: { params: { path: { questionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { questionId: string } } }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/quizzes/questions/{questionId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Question deletion failed') : null
  };
}

// POST /quizzes/questions/{questionId}/flag
// (already exists)

// POST /quizzes/questions/flags/{flagId}/resolve
export function useResolveFlaggedQuestion(): {
  mutate: (variables: { params: { path: { flagId: string } }, body: ResolveFlagBody }) => void,
  mutateAsync: (variables: { params: { path: { flagId: string } }, body: ResolveFlagBody }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/questions/flags/{flagId}/resolve");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to resolve flagged question') : null
  };
}

// --- Question Bank Controller Hooks ---

// POST /quizzes/question-bank
export function useCreateQuestionBank(): {
  mutate: (variables: { body: components['schemas']['CreateQuestionBankBody'] }) => void,
  mutateAsync: (variables: { body: components['schemas']['CreateQuestionBankBody'] }) => Promise<components['schemas']['CreateQuestionBankResponse']>,
  data: components['schemas']['CreateQuestionBankResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/question-bank/");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Question bank creation failed') : null
  };
}

// GET /quizzes/question-bank/{questionBankId}
export function useQuestionBankById(questionBankId: string): {
  data: components['schemas']['QuestionBankResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/question-bank/{questionBankId}", {
    params: { path: { questionBankId } }
  }, { enabled: !!questionBankId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch question bank') : null,
    refetch: result.refetch
  };
}

// PATCH /quizzes/question-bank/{questionBankId}/questions/{questionId}/add
export function useAddQuestionToBank(): {
  mutate: (variables: { params: { path: { questionBankId: string, questionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { questionBankId: string, questionId: string } } }) => Promise<components['schemas']['QuestionBankResponse']>,
  data: components['schemas']['QuestionBankResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/quizzes/question-bank/{questionBankId}/questions/{questionId}/add");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to add question to bank') : null
  };
}

// PATCH /quizzes/question-bank/{questionBankId}/questions/{questionId}/remove
export function useRemoveQuestionFromBank(): {
  mutate: (variables: { params: { path: { questionBankId: string, questionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { questionBankId: string, questionId: string } } }) => Promise<components['schemas']['QuestionBankResponse']>,
  data: components['schemas']['QuestionBankResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/quizzes/question-bank/{questionBankId}/questions/{questionId}/remove");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to remove question from bank') : null
  };
}

// PATCH /quizzes/question-bank/{questionBankId}/questions/{questionId}/replace-duplicate
export function useReplaceQuestionWithDuplicate(): {
  mutate: (variables: { params: { path: { questionBankId: string, questionId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { questionBankId: string, questionId: string } } }) => Promise<components['schemas']['ReplaceQuestionResponse']>,
  data: components['schemas']['ReplaceQuestionResponse'] | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/quizzes/question-bank/{questionBankId}/questions/{questionId}/replace-duplicate");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to replace question with duplicate') : null
  };
}

// --- Quiz Controller Hooks ---

// POST /quizzes/quiz/{quizId}/bank
export function useAddQuestionBankToQuiz(): {
  mutate: (variables: { params: { path: { quizId: string } }, body: components['schemas']['AddQuestionBankBody'] }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string } }, body: components['schemas']['AddQuestionBankBody'] }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/quiz/{quizId}/bank");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to add question bank to quiz') : null
  };
}

export function useGetProcotoringSettings(): {
  getSettings: (courseId: string, courseVersionId: string) => Promise<any>;
  settingLoading: boolean;
  settingError: string | null;
} {
  const [settingLoading, setSettingLoading] = useState(false);
  const [settingError, setSettingError] = useState<string | null>(null);

  const getSettings = async (
    courseId: string,
    courseVersionId: string
  ): Promise<any> => {
    setSettingLoading(true);
    setSettingError(null);

    try {
      const method = 'GET';
      const url = `${import.meta.env.VITE_BASE_URL}/setting/course-setting/${courseId}/${courseVersionId}/`;

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', 'authorization': `Bearer ${localStorage.getItem('firebase-auth-token')}` },
      });

      console.log(res);

      if (!res.ok) {
        throw new Error(`Failed to update settings: ${res.status}`);
      }

      return await res.json();
    } catch (err: any) {
      setSettingError(err.message || 'Unknown error');
    } finally {
      setSettingLoading(false);
    }
  };

  return { getSettings, settingLoading, settingError };
}

// DELETE /quizzes/quiz/{quizId}/bank/{questionBankId}
export function useRemoveQuestionBankFromQuiz(): {
  mutate: (variables: { params: { path: { quizId: string, questionBankId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string, questionBankId: string } } }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("delete", "/api/quizzes/quiz/{quizId}/bank/{questionBankId}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to remove question bank from quiz') : null
  };
}

// PATCH /quizzes/quiz/{quizId}/bank
export function useEditQuestionBankInQuiz(): {
  mutate: (variables: { params: { path: { quizId: string } }, body: components['schemas']['EditQuestionBankBody'] }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string } }, body: components['schemas']['EditQuestionBankBody'] }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("patch", "/api/quizzes/quiz/{quizId}/bank");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to edit question bank configuration') : null
  };
}

// GET /quizzes/quiz/{quizId}/bank
export function useGetAllQuestionBanksForQuiz(quizId: string): {
  data: components['schemas']['GetAllQuestionBanksResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/bank", {
    params: { path: { quizId } }
  }, { enabled: !!quizId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch question banks for quiz') : null,
    refetch: result.refetch
  };
}

// POST /quizzes/quiz/{quizId}/submission/{submissionId}/score/{score}
export function useUpdateQuizSubmissionScore(): {
  mutate: (variables: { params: { path: { quizId: string, submissionId: string, score: number } } }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string, submissionId: string, score: number } } }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/quiz/{quizId}/submission/{submissionId}/score/{score}");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to update submission score') : null
  };
}

// POST /quizzes/quiz/{quizId}/submission/{submissionId}/regrade
export function useRegradeQuizSubmission(): {
  mutate: (variables: { params: { path: { quizId: string, submissionId: string } }, body: components['schemas']['RegradeSubmissionBody'] }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string, submissionId: string } }, body: components['schemas']['RegradeSubmissionBody'] }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/quiz/{quizId}/submission/{submissionId}/regrade");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to regrade submission') : null
  };
}

// POST /quizzes/quiz/{quizId}/submission/{submissionId}/question/{questionId}/feedback
export function useAddFeedbackToQuizQuestion(): {
  mutate: (variables: { params: { path: { quizId: string, submissionId: string, questionId: string } }, body: components['schemas']['AddFeedbackBody'] }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string, submissionId: string, questionId: string } }, body: components['schemas']['AddFeedbackBody'] }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/quiz/{quizId}/submission/{submissionId}/question/{questionId}/feedback");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to add feedback to question') : null
  };
}

// POST /quizzes/quiz/{quizId}/user/{userId}/reset-attempts
export function useResetUserQuizAttempts(): {
  mutate: (variables: { params: { path: { quizId: string, userId: string } } }) => void,
  mutateAsync: (variables: { params: { path: { quizId: string, userId: string } } }) => Promise<void>,
  data: void | undefined,
  error: string | null,
  isPending: boolean,
  isSuccess: boolean,
  isError: boolean,
  isIdle: boolean,
  reset: () => void,
  status: 'idle' | 'pending' | 'success' | 'error'
} {
  const result = api.useMutation("post", "/api/quizzes/quiz/{quizId}/user/{userId}/reset-attempts");
  return {
    ...result,
    error: result.error ? (result.error.message || 'Failed to reset user quiz attempts') : null
  };
}

// --- Attempt Controller Hooks ---

// GET /quizzes/{quizId}/attempt/{attemptId}
export function useGetAttemptDetails(quizId: string, attemptId: string): {
  data: components['schemas']['GetAttemptResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/attempts/{attemptId}", {
    params: { path: { quizId, attemptId } }
  }, { enabled: !!quizId && !!attemptId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch attempt details') : null,
    refetch: result.refetch
  };
}

// GET /quizzes/{quizId}/analytics
export function useQuizAnalytics(quizId: string): {
  data: components['schemas']['QuizAnalyticsResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/analytics", {
    params: { path: { quizId } }
  }, { enabled: !!quizId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch quiz analytics') : null,
    refetch: result.refetch
  };
}

// GET /quizzes/{quizId}/details
export function useQuizDetails(quizId: string): {
  data: components['schemas']['QuizDetailsResponse'] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/details", {
    params: { path: { quizId } }
  }, { enabled: !!quizId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch quiz details') : null,
    refetch: result.refetch
  };
}

// GET /quizzes/{quizId}/performance
export function useQuizPerformance(quizId: string): {
  data: components['schemas']['QuizPerformanceResponse'][] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/performance", {
    params: { path: { quizId } }
  }, { enabled: !!quizId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch quiz performance') : null,
    refetch: result.refetch
  };
}

// Get /quizzes/{quizId}/results
export function useQuizResults(quizId: string): {
  data: components['schemas']['QuizResultsResponse'][] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/results", {
    params: { path: { quizId } }
  }, { enabled: !!quizId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch quiz results') : null,
    refetch: result.refetch
  };
}

export function useQuizSubmissions(quizId: string): {
  data: components['schemas']['GetAllSubmissionsResponse'][] | undefined,
  isLoading: boolean,
  error: string | null,
  refetch: () => void
} {
  const result = api.useQuery("get", "/api/quizzes/quiz/{quizId}/submissions", {
    params: { path: { quizId } }
  }, { enabled: !!quizId });

  return {
    data: result.data,
    isLoading: result.isLoading,
    error: result.error ? (result.error.message || 'Failed to fetch quiz submissions') : null,
    refetch: result.refetch
  };
}

