name: Backend CI/CD

on:
  push:
    branches: [master, staging, test-cicd]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-all.yml'
  workflow_dispatch:

# Set permissions for the workflow
permissions:
  contents: write  # Required for creating tags
  packages: write  # Required for pushing to Docker Hub
  id-token: write  # Required for OIDC authentication

env:
  NODE_VERSION: '22'
  DOCKER_IMAGE: vibe-backend
  GCP_REGION: asia-south2
  GCP_SERVICE: vibe-backend

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version || steps.fallback_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          release_branches: main,staging,test-cicd
          default_bump: patch
          tag_prefix: ''
          fetch_all_tags: true
          create_annotated_tag: true
          dry_run: false
      
      # Fallback to use current date as version if tag creation fails
      - name: Set fallback version if tagging failed
        if: steps.tag_version.outcome == 'failure'
        id: fallback_version
        run: echo "new_version=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

  build:
    name: Build and Push
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js for potential pre-build steps
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # Install any missing dependencies if needed
      - name: Install dependencies
        run: |
          cd backend
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "Creating empty pnpm-lock.yaml file"
            touch pnpm-lock.yaml
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ needs.versioning.outputs.new_version }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            SENTRY_AUTH_TOKEN=${{ env.SENTRY_AUTH_TOKEN }}
          allow-failure: true

  deploy_staging:
    name: Deploy to Staging
    needs: [versioning, build]
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Deploy to Firebase (staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        with:
          repoToken: '${{ env.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: 'staging'
          projectId: '${{ env.FIREBASE_PROJECT_ID }}'
          target: 'staging'

  deploy_production:
    name: Deploy to Production
    needs: [versioning, build, deploy_staging]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: google-github-actions/auth@v2
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Deploy to Firebase (production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        with:
          repoToken: '${{ env.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ env.FIREBASE_PROJECT_ID }}'
